# PluginPilot Main Configuration

# General settings
messages-prefix: "&6[PluginPilot]&r "
default-language: "en"
allow-external-sources: true
debug-mode: false

# Storage settings
database:
  type: sqlite
  filename: "pluginpilot.db"

# Update/backup settings
auto-update:
  enabled: true
  check-interval-minutes: 60
  include-self: true
  exception-list:
    - "PluginPilot"
    - "Vault"
    # Add plugin names here to exclude from auto-updates

backups:
  enabled: true
  keep-last: 3
  auto-backup-before-update: true

# Auto-detection of manually added/removed plugins
auto-detection:
  enabled: true
  check-interval-minutes: 1 
  notify-admins: true

# Malware scanner (under development)
security:
  scan-on-download: true
  scan-api-url: "https://api.virustotal.com/api/v3/files"
  api-key: "your-virustotal-api-key-here"
  fail-on-suspicious: true

# Plugin repositories
repositories:
  - id: "spigotmc"
    enabled: false
    api-url: "https://api.spigotmc.org/legacy/update.php"
    # SpigotMC integration is currently under development
  - id: "modrinth"
    enabled: true
    api-url: "https://api.modrinth.com/v2"
  - id: "polymart"
    enabled: false
    api-url: "https://api.polymart.org/v1"
    # Polymart integration is currently under development
  - id: "hangar"
    enabled: true
    api-url: "https://hangar.papermc.io/api/v1"
    #custom sources in development.
  - id: "custom"
    enabled: false
    api-url: "https://api.github.com/repos"
    custom-sources:
      jenkins:
        enabled: false
        base-url: "https://ci.example.com/job"
        artifact-path: "lastSuccessfulBuild/artifact"
      github:
        enabled: false
        base-url: "https://api.github.com/repos"
        token: "your-github-token-here"
      direct-url:
        enabled: false
        urls:
          - "https://example.com/plugins/{plugin}.jar"
          - "https://cdn.example.com/downloads/{plugin}-{version}.jar"

# Cache settings
cache:
  search-results-ttl-minutes: 30
  plugin-info-ttl-minutes: 60
  max-search-results: 100

# Server type filtering
allowed-server-types: "bukkit,spigot,paper"
# Comma-separated list of server types to include in search results
# Available options: bukkit, spigot, paper

# Tab completion settings
tab-completion:
  async-search: true
  search-delay-ms: 500
  loading-message: "Loading..."
  max-suggestions: 100